import{S as v,a as w,i as c}from"./assets/vendor-B3Lscd_h.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more");let E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:i,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${q}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),E.refresh()}function M(){m.innerHTML=""}function p(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}function L(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}const P="28903135-2e38ca847315cff4cdbf6a245",B="https://pixabay.com/api/";async function b(o,t){const s={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await w.get(B,{params:s})).data}const $=document.querySelector(".form");document.querySelector(".gallery");const O=document.querySelector(".load-more");let l="",a=1,f=0;const x=15;$.addEventListener("submit",A);O.addEventListener("click",_);async function A(o){if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){c.warning({message:"Enter a search query!"});return}a=1,M(),u(),p();try{const t=await b(l,a);if(d(),t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(t.hits),f=Math.ceil(t.totalHits/x),a<f&&L()}catch{d(),c.error({message:"Error fetching data!"})}}async function _(){a+=1,u(),p();try{const o=await b(l,a);g(o.hits),d(),a>=f?(u(),c.info({message:"We're sorry, but you've reached the end of search results."})):L();const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{d(),c.error({message:"Error loading more images!"})}}
//# sourceMappingURL=index.js.map
